version: "3.8"
services:
  front:
    build: ../react/mui-4
    ports:
      - 3000:3000
    environment:
      DB_URL : postgres://db/mui-4
    volumes:
      - ../react/mui-4:/home/app
  db:
    build: ../postgres  
    ports:
      - 5432:5432
volumes:
  source:
